version: '3.8'

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT:-8080}:8080"
    volumes:
      - h2-data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - ORACLE_HOST=${ORACLE_HOST:-localhost}
      - ORACLE_PORT=${ORACLE_PORT:-1521}
      - ORACLE_SERVICE=${ORACLE_SERVICE:-XE}
      - ORACLE_USER=${ORACLE_USER:-system}
      - JAVA_OPTS=${JAVA_OPTS:-"-Xmx512m -Xms256m"}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl-certs:/etc/nginx/ssl
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    depends_on:
      - app
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  h2-data:
  prometheus_data:
  grafana_data:
  ssl-certs:

networks:
  app-network:
    driver: bridge 